# Copyright © 2021 InfinitzHost
#
# Licensed under the MIT License;
# you may not use this file except in compliance with the License.

site_name: InfinitzHost Knowledgebase
theme:
  name: material
  logo: https://avatars.githubusercontent.com/u/76196261?s=88&v=4
  favicon: https://avatars.githubusercontent.com/u/76196261?s=88&v=4
  palette:
    scheme: slate
    primary: deep purple
    accent: cyan
  generator: false
copyright: Copyright &copy; 2021 InfinitzHost
repo_url: https://github.com/InfinitzHost/Knowledgebase
markdown_extensions:
  - admonition
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/InfinitzHost
    
