site_name: InfinitzHost Knowledgebase
theme:
  name: material
  palette:
    scheme: slate
    primary: cyan
    accent: red
  generator: false
copyright: Copyright &copy; 2021 InfinitzHost
repo_url: https://github.com/InfinitzHost/Knowledgebase
markdown_extensions:
  - admonition